primaryBranch: main
releaseType: java-yoshi
handleGHRelease: true
last-release-sha: 103846dbe135790a59788a5ae3bafe56ededba3e
extraFiles: [
  "README.adoc",
  "spring-cloud-generator/scripts/resources/googleapis_modification_string.txt"
]
branches:
  - releaseType: java-yoshi
    handleGHRelease: true
    branch: 3.x
    extraFiles: ["README.adoc"]
  - releaseType: java-yoshi
    handleGHRelease: true
    branch: 4.x
    extraFiles: ["README.adoc"]
